#!/usr/bin/env bash
set -euo pipefail

# This script may delete only its own disposable project on a GitHub-hosted CI runner.
if [[ "${GITHUB_ACTIONS:-}" != "true" || "${RUNNER_ENVIRONMENT:-}" != "github-hosted" || -z "${GITHUB_RUN_ID:-}" || -z "${RUNNER_TEMP:-}" ]]; then
  printf 'migration smoke requires an isolated GitHub Actions runner\n' >&2
  exit 1
fi

project="smarthelp-migration-ci-${GITHUB_RUN_ID}-${GITHUB_RUN_ATTEMPT:-1}"
envfile="$(mktemp "${RUNNER_TEMP}/smarthelp-db-env.XXXXXX")"
chmod 600 "$envfile"
compose=(docker compose --env-file "$envfile" --project-name "$project")
created=0
cleanup() {
  local cleanup_failed=0
  if [[ "$created" == 1 ]]; then
    "${compose[@]}" down --volumes --remove-orphans || cleanup_failed=1
  fi
  rm -f "$envfile"
  if [[ "$cleanup_failed" == 1 ]]; then
    printf 'synthetic CI Compose cleanup failed\n' >&2
    exit 1
  fi
}
trap cleanup EXIT

python3 - "$envfile" <<'PY'
import secrets
import sys

with open(sys.argv[1], 'w', encoding='utf-8') as handle:
    handle.write('POSTGRES_USER=smarthelp_ci\nPOSTGRES_DB=smarthelp_ci\n')
    handle.write(f'POSTGRES_PASSWORD={secrets.token_urlsafe(32)}\n')
    handle.write('PGADMIN_DEFAULT_EMAIL=ci@smarthelp.dev\n')
    handle.write(f'PGADMIN_DEFAULT_PASSWORD={secrets.token_urlsafe(32)}\n')
PY

# The envfile is generated by this script with URL-safe random tokens, not user input.
source "$envfile"
export POSTGRES_PORT=5432 PGADMIN_PORT=5050
export DATABASE_URL="postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@127.0.0.1:5432/${POSTGRES_DB}?schema=public"
if [[ -n "$("${compose[@]}" ps --all --quiet)" ]] || docker volume inspect "${project}_postgres_data" >/dev/null 2>&1 || docker volume inspect "${project}_pgadmin_data" >/dev/null 2>&1 || docker network inspect "${project}_default" >/dev/null 2>&1; then
  printf 'refusing to reuse existing Compose containers, volumes or network\n' >&2
  exit 1
fi
"${compose[@]}" config --quiet
assert_owned_target() {
  local container published
  container="$("${compose[@]}" ps --quiet postgres)"
  [[ -n "$container" ]] || { printf 'CI PostgreSQL container missing\n' >&2; return 1; }
  [[ "$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$container")" == "$project" ]] || return 1
  [[ "$(docker inspect --format '{{.State.Health.Status}}' "$container")" == healthy ]] || return 1
  published="$(docker port "$container" 5432/tcp)"
  [[ "$published" == '127.0.0.1:5432' ]] || { printf 'unexpected CI PostgreSQL port mapping\n' >&2; return 1; }
}
created=1
"${compose[@]}" up --detach --wait postgres
assert_owned_target
npx prisma migrate deploy
npx prisma migrate status
node scripts/ci/migration-check.mjs create

"${compose[@]}" down
"${compose[@]}" up --detach --wait postgres
assert_owned_target
node scripts/ci/migration-check.mjs persisted

# This project was created above with random credentials; rebuilding proves empty-state reproducibility.
"${compose[@]}" down --volumes
"${compose[@]}" up --detach --wait postgres
assert_owned_target
npx prisma migrate deploy
node scripts/ci/migration-check.mjs create
printf 'synthetic migration, relationships, persistence and empty-state rebuild passed\n'
